### ISSUE TITLE
Percona-XtraDB-Cluster installation fails.

### ISSUE THREAD

**Issue by jarjis** [jayjanssen/vagrant-percona#4]
I'm using https://github.com/jayjanssen/vagrant-percona/blob/c36e1bb00ad5455d544a460e4095a4b51d5bdacc/puppet/modules/percona/manifests/repository.pp on CentOS 6.4 can't seems to get it installed. 

Notice: /Stage[main]/Profile::Db::Percona::Cluster::Packages/Package[Percona-Server-shared-51]/ensure: created
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install Percona-XtraDB-Cluster-shared-55.x86_64' returned 1: Error: Percona-XtraDB-Cluster-shared-55 confli
cts with 1:Percona-XtraDB-Cluster-shared-56-5.6.14-25.1.596.rhel6.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Error: /Stage[main]/Profile::Db::Percona::Cluster::Packages/Package[Percona-XtraDB-Cluster-shared-55.x86_64]/ensure: change from absent to present failed:
 Execution of '/usr/bin/yum -d 0 -e 0 -y install Percona-XtraDB-Cluster-shared-55.x86_64' returned 1: Error: Percona-XtraDB-Cluster-shared-55 conflicts wi
th 1:Percona-XtraDB-Cluster-shared-56-5.6.14-25.1.596.rhel6.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by jayjanssen** [comment]
I'd need more context to understand the issue (you're clearly not using my puppet modules in this vagrant environment).  At face-value, your issue seems to be that the 56 version of the package conflicts with the version you are trying to install (55).  You need to uninstall the 56 version first.  If this is a fresh environment, then that 56 version is coming from somewhere first and you need to figure out where.

**Comment by grypyrg** [comment]
It seems indeed that this is different puppet code.
The hints from Jay (package conflicts) seems reasonable. Closing.
